"use strict";

const canvas = document.querySelector("#game-canvas");
const context = canvas.getContext("2d");
const board = { width: canvas.width, height: canvas.height, cell: 20, columns: 36, rows: 24 };
const directions = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } };
const opposite = { up: "down", down: "up", left: "right", right: "left" };
const game = { state: "ready", snake: [], direction: "right", queuedDirection: "right", food: null, score: 0, highScore: Number(localStorage.getItem("esbi-worm-high-score") || 0), enemies: [], lastFrame: 0, moveAccumulator: 0, explosionStartedAt: 0, respawnAt: 0, nextExplosionAt: 0, frameId: 0 };
const ui = { score: document.querySelector("#score"), highScore: document.querySelector("#high-score"), status: document.querySelector("#game-status"), overlay: document.querySelector("#game-overlay"), start: document.querySelector("#start-game"), pause: document.querySelector("#pause-game"), restart: document.querySelector("#restart-game") };

function randomInt(max) { return Math.floor(Math.random() * max); }
function cellCenter(cell) { return { x: cell.x * board.cell + board.cell / 2, y: cell.y * board.cell + board.cell / 2 }; }
function distance(a, b) { return Math.hypot(a.x - b.x, a.y - b.y); }
function occupied(cell) { return (game.food && game.food.x === cell.x && game.food.y === cell.y) || game.snake.some(part => part.x === cell.x && part.y === cell.y) || game.enemies.some(enemy => Math.floor(enemy.x / board.cell) === cell.x && Math.floor(enemy.y / board.cell) === cell.y); }
function randomFreeCell() { let cell; let attempts = 0; do { cell = { x: randomInt(board.columns), y: randomInt(board.rows) }; attempts += 1; } while (occupied(cell) && attempts < 500); return cell; }
function updateScore() { ui.score.textContent = String(game.score); ui.highScore.textContent = String(game.highScore); }
function setStatus(message) { ui.status.textContent = message; }
function setOverlay(title, description, hidden) { ui.overlay.querySelector("strong").textContent = title; ui.overlay.querySelector("span").textContent = description; ui.overlay.classList.toggle("is-hidden", hidden); }

function createEnemies() { game.enemies = []; for (let i = 0; i < 4; i += 1) { const cell = randomFreeCell(); const angle = Math.random() * Math.PI * 2; game.enemies.push({ x: cell.x * board.cell + board.cell / 2, y: cell.y * board.cell + board.cell / 2, vx: Math.cos(angle) * 42, vy: Math.sin(angle) * 42, radius: 9, phase: i * 1.4 }); } }
function resetGame() { game.state = "ready"; game.snake = [{ x: 8, y: 12 }, { x: 7, y: 12 }, { x: 6, y: 12 }]; game.direction = "right"; game.queuedDirection = "right"; game.score = 0; game.food = randomFreeCell(); game.enemies = []; game.explosionStartedAt = 0; game.respawnAt = 0; game.nextExplosionAt = 0; updateScore(); createEnemies(); setStatus("시작 버튼을 눌러 게임을 시작하세요."); setOverlay("Ready?", "키보드 방향키·WASD 또는 아래 버튼으로 조작하세요.", false); ui.start.disabled = false; ui.pause.disabled = true; draw(); }
function startGame() { if (game.state === "running") return; if (game.state === "over") resetGame(); game.state = "running"; game.lastFrame = performance.now(); game.nextExplosionAt = game.lastFrame + 6000; setStatus("게임 진행 중 · 적과 폭발을 피하세요."); setOverlay("", "", true); ui.start.disabled = true; ui.pause.disabled = false; game.frameId = requestAnimationFrame(gameLoop); }
function togglePause() { if (game.state === "running") { game.state = "paused"; ui.pause.textContent = "계속하기"; setStatus("일시정지되었습니다."); setOverlay("Paused", "계속하기 버튼을 눌러 이어가세요.", false); } else if (game.state === "paused") { game.state = "running"; ui.pause.textContent = "일시정지"; game.lastFrame = performance.now(); setStatus("게임 진행 중 · 적과 폭발을 피하세요."); setOverlay("", "", true); game.frameId = requestAnimationFrame(gameLoop); } }
function endGame(message) { game.state = "over"; if (game.score > game.highScore) { game.highScore = game.score; localStorage.setItem("esbi-worm-high-score", String(game.highScore)); } updateScore(); ui.pause.disabled = true; ui.start.disabled = false; setStatus(message); setOverlay("Game over", "재시작 버튼으로 다시 도전하세요.", false); draw(); }
function setDirection(name) { if (!directions[name] || game.state === "over") return; if (opposite[game.direction] !== name) game.queuedDirection = name; }
function moveSnake() { game.direction = game.queuedDirection; const delta = directions[game.direction]; const head = { x: game.snake[0].x + delta.x, y: game.snake[0].y + delta.y }; if (head.x < 0 || head.y < 0 || head.x >= board.columns || head.y >= board.rows || game.snake.some(part => part.x === head.x && part.y === head.y)) { endGame("벽 또는 자기 몸에 닿았습니다."); return; } game.snake.unshift(head); if (head.x === game.food.x && head.y === game.food.y) { game.score += 10; if (game.score > game.highScore) game.highScore = game.score; game.food = randomFreeCell(); updateScore(); } else { game.snake.pop(); } }
function moveEnemies(delta) { for (const enemy of game.enemies) { enemy.x += enemy.vx * delta; enemy.y += enemy.vy * delta; if (enemy.x < enemy.radius || enemy.x > board.width - enemy.radius) { enemy.vx *= -1; enemy.x = Math.max(enemy.radius, Math.min(board.width - enemy.radius, enemy.x)); } if (enemy.y < enemy.radius || enemy.y > board.height - enemy.radius) { enemy.vy *= -1; enemy.y = Math.max(enemy.radius, Math.min(board.height - enemy.radius, enemy.y)); } } for (let a = 0; a < game.enemies.length; a += 1) for (let b = a + 1; b < game.enemies.length; b += 1) { const first = game.enemies[a]; const second = game.enemies[b]; if (distance(first, second) < first.radius + second.radius) { const firstVx = first.vx; const firstVy = first.vy; first.vx = -second.vx; first.vy = -second.vy; second.vx = -firstVx; second.vy = -firstVy; } } }
function checkEnemyCollision() { const head = cellCenter(game.snake[0]); if (game.enemies.some(enemy => distance(head, enemy) < enemy.radius + board.cell * .42)) { endGame("적에게 닿았습니다."); return true; } return false; }
function beginExplosion(now) { game.explosionStartedAt = now; game.respawnAt = now + 2000; setStatus("폭발! 안전한 곳으로 이동하세요."); }
function respawnEnemies(now) { if (now < game.respawnAt) return; createEnemies(); game.explosionStartedAt = 0; game.respawnAt = 0; game.nextExplosionAt = now + 6000; setStatus("적들이 다시 나타났습니다."); }
function checkExplosionCollision() { if (!game.explosionStartedAt) return false; const head = cellCenter(game.snake[0]); if (game.enemies.some(enemy => distance(head, enemy) < 70)) { endGame("폭발에 닿았습니다."); return true; } return false; }
function update(now) { const delta = Math.min((now - game.lastFrame) / 1000, .1); game.lastFrame = now; if (game.explosionStartedAt) { checkExplosionCollision(); respawnEnemies(now); return; } if (now >= game.nextExplosionAt) { beginExplosion(now); return; } game.moveAccumulator += delta; if (game.moveAccumulator >= .12) { game.moveAccumulator = 0; moveSnake(); } if (game.state !== "running") return; moveEnemies(delta); checkEnemyCollision(); }
function drawGrid() { context.strokeStyle = "rgba(143,168,255,.055)"; context.lineWidth = 1; for (let x = 0; x <= board.width; x += board.cell) { context.beginPath(); context.moveTo(x, 0); context.lineTo(x, board.height); context.stroke(); } for (let y = 0; y <= board.height; y += board.cell) { context.beginPath(); context.moveTo(0, y); context.lineTo(board.width, y); context.stroke(); } }
function drawCircle(point, radius, fill, stroke) { context.beginPath(); context.arc(point.x, point.y, radius, 0, Math.PI * 2); context.fillStyle = fill; context.fill(); if (stroke) { context.strokeStyle = stroke; context.stroke(); } }
function draw() { context.clearRect(0, 0, board.width, board.height); context.fillStyle = "#070b16"; context.fillRect(0, 0, board.width, board.height); drawGrid(); if (game.food) { const food = cellCenter(game.food); drawCircle(food, 6, "#62e4dc"); drawCircle(food, 11, "rgba(98,228,220,.16)"); } game.snake.forEach((part, index) => { const point = cellCenter(part); drawCircle(point, index === 0 ? 9 : 8, index === 0 ? "#c1ceff" : "#8fa8ff"); }); if (game.explosionStartedAt) { game.enemies.forEach(enemy => { const pulse = 28 + Math.sin(performance.now() / 100) * 5; drawCircle(enemy, pulse, "rgba(255,126,180,.14)", "rgba(255,126,180,.8)"); drawCircle(enemy, 8, "#ff7eb4"); }); } else { game.enemies.forEach(enemy => { drawCircle(enemy, enemy.radius + 3, "rgba(255,126,180,.12)"); drawCircle(enemy, enemy.radius, "#ff7eb4"); }); } }
function gameLoop(now) { if (game.state !== "running") return; update(now); draw(); if (game.state === "running") game.frameId = requestAnimationFrame(gameLoop); }

document.querySelectorAll("[data-direction]").forEach(button => button.addEventListener("pointerdown", event => { event.preventDefault(); setDirection(button.dataset.direction); }));
document.addEventListener("keydown", event => { const keys = { ArrowUp: "up", w: "up", W: "up", ArrowDown: "down", s: "down", S: "down", ArrowLeft: "left", a: "left", A: "left", ArrowRight: "right", d: "right", D: "right" }; if (keys[event.key]) { event.preventDefault(); setDirection(keys[event.key]); } if (event.key === " " && (game.state === "running" || game.state === "paused")) { event.preventDefault(); togglePause(); } });
ui.start.addEventListener("click", startGame); ui.pause.addEventListener("click", togglePause); ui.restart.addEventListener("click", () => { cancelAnimationFrame(game.frameId); resetGame(); startGame(); });
const menuToggle = document.querySelector(".menu-toggle"); const siteNav = document.querySelector("#site-nav"); menuToggle.addEventListener("click", () => { const isOpen = siteNav.classList.toggle("is-open"); menuToggle.setAttribute("aria-expanded", String(isOpen)); }); siteNav.addEventListener("click", () => { siteNav.classList.remove("is-open"); menuToggle.setAttribute("aria-expanded", "false"); });
document.querySelector("#current-year").textContent = new Date().getFullYear(); ui.highScore.textContent = String(game.highScore); resetGame();
